### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by gbrunacci** [ctkc/findyourservice#1]
A few notes:
- Controllers (and any class) name must be `StudlyCaps`. This also applies to file names.
- Functions and methods must be `camelCase`
  - The only exception here is eloquent/database attributes and get/post parameters where they must be `snake_case`
- Views directory and blade file name must be separated by dash. Example `error-message.blade.php`

Further Reading:
http://www.laravelbestpractices.com/#code_style_guide
http://www.laravelbestpractices.com/#table_and_field_naming

**Comment by ctkc** [comment]
Corrected!
